language: cpp

compiler:
  - gcc

env:
  - LOG_PKG=liblog4cplus-dev
  - LOG_PKG=liblog4cxx10-dev
  - LOG_PKG=liblog4cpp5-dev
  - LOG_CFG=--with-ostream-logging

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-all-dev libcurl3-dev ${LOG_PKG}

before_script:
  - ./autogen.sh

script:
  - ./configure ${LOG_CFG} && make -j4 && make -j4 check
