language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-all-dev libcurl3-dev liblog4cplus-dev

before_script:
  - ./autogen.sh

script:
  - ./configure && make -j4 && make -j4 check
