language: cpp

compiler:
  - gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libboost-all-dev libcurl3-dev

script:
  - ./autogen.sh
  - ./configure --disable-logging && make -j$(nproc) && make check
